const popular = [
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
];
const popular1 = [
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
];
const aparel1 = [
  {
    item1a: "Shirt(Launder and Press)",
    price1a: 1250,
  },
  {
    item2a: "Shirt(Launder and Press)",
    price2a: 1250,
  },
  {
    item3a: "Shirt(Launder and Press)",
    price3a: 1250,
  },
  {
    item4a: "Shirt(Launder and Press)",
    price4a: 1250,
  },
  {
    item5a: "Shirt(Launder and Press)",
    price5a: 1250,
  },
  {
    item6a: "Shirt(Launder and Press)",
    price6a: 1250,
  },
  {
    item7a: "Shirt(Launder and Press)",
    price7a: 1250,
  },
  {
    item8a: "Shirt(Launder and Press)",
    price8a: 1250,
  },
];
const aparel2 = [
  {
    item1b: "Shirt(Launder and Press)",
    price1b: 1250,
  },
  {
    item2b: "Shirt(Launder and Press)",
    price2b: 1250,
  },
  {
    item3b: "Shirt(Launder and Press)",
    price3b: 1250,
  },
  {
    item4b: "Shirt(Launder and Press)",
    price4b: 1250,
  },
  {
    item5b: "Shirt(Launder and Press)",
    price5b: 1250,
  },
  {
    item6b: "Shirt(Launder and Press)",
    price6b: 1250,
  },
  {
    item7b: "Shirt(Launder and Press)",
    price7b: 1250,
  },
  {
    item8b: "Shirt(Launder and Press)",
    price8b: 1250,
  },
];

export const people = [
  {
    img: "./img/laundry/clothes-4617456_1280.png",
    title: "product manager",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis? `,
  },
  {
    img: "./img/laundry/clothes-4617456_1280.pn",
    title: "developer",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis?`,
  },
  {
    img: "./img/laundry/daniele-bissoli-u25sfT6lv-Q-unsplash.jpg",
    title: "designer",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis?`,
  },
  {
    img: "./img/laundry/pxfuel.jpg",
    title: "designer",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis?`,
  },
];

export const items = [
  {
    question: "What services do you offer?",
    class1: "fas fa-minus-square",
    class2: "fas fa-plus-square",
    answer:
      "we offer washing,drying,foldong, and ironing services for your clothing.",
    number: 200,
  },
  {
    question: "How does your pricing work?",
    class1: "fas fa-minus-square",
    class2: "fas fa-plus-square",
    answer:
      "Pricing is typically based on the weight of your laundry, the type of items,and any additional services you require. You can find our pricing details on our website or by contacting us directly.",
    number: 300,
  },
  {
    question: "Is my laudry safe with you?",
    class1: "fas fa-minus-square",
    class2: "fas fa-plus-square",
    answer:
      "Yes, we take great care in handling your laundry. Our staff is trained to maintain the highest standards of quality and security.",
    number: 400,
  },
  {
    question: "Do you offer any discounts?",
    class1: "fas fa-minus-square",
    class2: "fas fa-plus-square",
    answer:
      "We often have promotions and loyatly programs for regular customers. Check our website or inquire anout current offers.",
    number: 500,
  },
  {
    question: "How can I pay for your services?",
    class1: "fas fa-minus-square",
    class2: "fas fa-plus-square",
    answer:
      "We accept various payment methods, including credit card, online payments,and cah on delivery.",
    number: 600,
  },
  {
    question: "How do I contact your customer support?",
    class1: "fas fa-minus-square",
    class2: "fas fa-plus-square",
    answer:
      "You can reach our customer support team via phone, email or through our website.",
    number: 700,
  },
];
